# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"make_bed_file": "intersect_annotations.ipynb",
         "intersect_files_using_bedtools": "intersect_annotations.ipynb",
         "closest_annotation_to_variant": "intersect_annotations.ipynb"}

modules = ["intersect_annotations.py"]

doc_url = "https://hjacobs3.github.io/SMS/"

git_url = "https://github.com/hjacobs3/SMS/tree/master/"

def custom_doc_links(name): return None
