# AUTOGENERATED! DO NOT EDIT! File to edit: 05_calculate_distances_to_splice_sites.ipynb (unless otherwise specified).

__all__ = ['leafcutter']

# Cell
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm
import seaborn as sns
sns.set()
import pandas as pd


# Cell
def leafcutter(variants_affecting_skipped_exons_within_5kb):


    import re
    list_of_cords_in_cluster=[]

    for final_phenotype_id in variants_affecting_skipped_exons_within_5kb.final_phenotype_id:


# Using re.split()
# Splitting characters in String
        split_list = re.split(', |:|_|!', final_phenotype_id)
        split_list=split_list[2:]

        cords_given_cluster = [ int(elem) for elem in split_list if 'chr' not in elem]

        list_of_cords_in_cluster.append(cords_given_cluster)


#assign to df
    variants_affecting_skipped_exons_within_5kb['location_of_introns_in_cluster'] = list_of_cords_in_cluster

    sorted_intron_locations=variants_affecting_skipped_exons_within_5kb.location_of_introns_in_cluster.apply(lambda x: sorted(x))

    variants_affecting_skipped_exons_within_5kb=variants_affecting_skipped_exons_within_5kb.assign(location_of_introns_in_cluster=sorted_intron_locations)


#calc the distance from the cluster locations and the variant
    variant_distance_from_splice_sites_in_cluster=variants_affecting_skipped_exons_within_5kb.apply(lambda x: [x['v_start'] - elem for elem in x['location_of_introns_in_cluster']], axis=1)

    variants_affecting_skipped_exons_within_5kb=variants_affecting_skipped_exons_within_5kb.assign(variant_distance_from_splice_sites_in_cluster=variant_distance_from_splice_sites_in_cluster)

    min_dis_to_splice_site_within_cluster=variants_affecting_skipped_exons_within_5kb['variant_distance_from_splice_sites_in_cluster'].apply(lambda x: min(x, key=abs ))

    variants_affecting_skipped_exons_within_5kb=variants_affecting_skipped_exons_within_5kb.assign(min_dis_to_splice_site_within_cluster=min_dis_to_splice_site_within_cluster)

    return variants_affecting_skipped_exons_within_5kb
