# AUTOGENERATED! DO NOT EDIT! File to edit: intersect_annotations.ipynb (unless otherwise specified).

__all__ = ['make_bed_file', 'intersect_files_using_bedtools', 'closest_annotation_to_variant']

# Cell
def make_bed_file(df, num_bp, info, no_strand):

    start=df.v_start.astype('int')
    end=df.v_end.astype('int')
    df['score']=[1]*len(df)
    df['strand']= df['strand'].str.replace('r','-')
    df['strand']= df['strand'].str.replace('f','+')
    if no_strand==True:
        forBed=pd.concat([df.chromosome, start, end, df[info], df.score, df.strand], axis=1)

    else:
        forBed=pd.concat([df.chromosome, start, end, df[info]], axis=1)
    return forBed




# Cell
def intersect_files_using_bedtools(a_file, b_file, directory_a, directory_b, overlap):
    import pybedtools
    if directory_a=='':
        directory_a='/Users/hnjacobs/Dropbox (MIT)/GradSchool/Finuance/SMS_project/scripts/data/'
    if directory_b=='':
        directory_b='/Users/hnjacobs/Dropbox (MIT)/GradSchool/Finuance/SMS_project/scripts/data/inputs/intersect/hg38/'

#intersect using pybedtools
    a = pybedtools.example_bedtool(directory_a+a_file)
    b = pybedtools.example_bedtool(directory_b+b_file)
#Then do the intersection with the BedTool.intersect() method:

    if overlap=='perfect':
#r paramater is that 100% of intron needs to intersect
        a_and_b = a.intersect(b,  wb=True, wa=True, r=True, f=0.99, e=False)
    elif overlap=='SNPs':
        a_and_b = a.intersect(b,  wb=True, wa=True, s=True)

    a_and_b.saveas(annotation_file+'-intersected-with-'+SNP_file)

# Cell
def closest_annotation_to_variant(a_file, b_file, directory_a, directory_b, overlap):
    import pybedtools
    if directory_a=='':
        directory_a='/Users/hnjacobs/Dropbox (MIT)/GradSchool/Finuance/SMS_project/scripts/data/'
    if directory_b=='':
        directory_b='/Users/hnjacobs/Dropbox (MIT)/GradSchool/Finuance/SMS_project/scripts/data/inputs/intersect/hg38/'

#import file pybedtools

    a = pybedtools.example_bedtool(directory_a+a_file)
    b = pybedtools.example_bedtool(directory_b+b_file)

#Then do the closest with the BedTool.closest() method, calculate distances

    a_and_b = a.closest(b,  a=True, D=True, s=True)

    a_and_b.saveas(annotation_file+'-closest-to-'+SNP_file)

