# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_cmap": "00_plots.ipynb",
         "PrC_curve": "00_plots.ipynb",
         "plot_ROC_based_on_annotation": "00_plots.ipynb",
         "plot_percent_annot_aganist_pip_bins": "01_intersect_annotations.ipynb",
         "ecdf": "00_plots.ipynb",
         "upset_plot": "00_plots.ipynb",
         "example": "00_plots.ipynb",
         "make_bed_file_given_window": "01_intersect_annotations.ipynb",
         "intersect_bedtools": "01_intersect_annotations.ipynb",
         "closest_bedtools": "01_intersect_annotations.ipynb",
         "get_fasta_bedtools": "02_identfiy_splice.ipynb",
         "gc_content": "02_identfiy_splice.ipynb",
         "sliding_window_along_sequence": "02_identfiy_splice.ipynb",
         "compute_maxent_on_data": "02_identfiy_splice.ipynb",
         "define_ss_gencode": "02_identfiy_splice.ipynb",
         "define_ss_leafcutter": "02_identfiy_splice.ipynb",
         "bootstrap_matching": "04_matching.ipynb",
         "plot_bootstraps": "04_matching.ipynb",
         "leafcutter": "05_calculate_distances_to_splice_sites.ipynb",
         "run_model": "06_GLM.ipynb",
         "run_model_bin_distance": "06_GLM.ipynb",
         "null_model_given_training_set": "06_GLM.ipynb",
         "print_puesdo_r": "06_GLM.ipynb",
         "get_tp_pp": "06_GLM.ipynb",
         "run_prc_over_thresholds": "06_GLM.ipynb",
         "get_percision_given_prc_curve": "06_GLM.ipynb"}

modules = ["plots.py",
           "intersect_annotations.py",
           "identify_splice.py",
           "match.py",
           "distance.py",
           "GLM.py"]

doc_url = "https://hjacobs3.github.io/SMS/"

git_url = "https://github.com/hjacobs3/SMS/tree/master/"

def custom_doc_links(name): return None
