# Autogenerated by nbdev

d = { 'settings': { 'branch': 'initial commit',
                'doc_baseurl': '/SMS',
                'doc_host': 'https://hannah.nicole.jacobs.github.io',
                'git_url': 'https://github.com/hannah.nicole.jacobs/SMS',
                'lib_path': 'SMS'},
  'syms': {'SMS.core': {'SMS.core.foo': ('core.html#foo', 'SMS/core.py')}}}
